package:
  name: gneiss
  version: 0.1.0

source:
  git_url: https://github.com/biocore/gneiss.git


requirements:
  build:
    - python
    - scikit-bio ==0.4.2
    - pandas
    - scipy
    - numpy
    - matplotlib
    - pyqt
  run:
    - python
    - scikit-bio ==0.4.2
    - pandas
    - scipy
    - numpy
    - matplotlib
    - pyqt
test:
  # Python imports
  imports:
    - gneiss

about:
  home: https://github.com/biocore/gneiss
  license: GPLv3 License
  summary: Compositional Analysis and Visualization toolkit
