os:
- linux
- osx
env:
  matrix:
  - CONDA_PY=35  CONDA_NPY=110
  global:
    secure: BYNKp1fpLXZMfkrSpt8MZfqFFNr69t0Oj2sFqeHITlHqul43OLSRhYUpLYmKEz/r21ppDtMeWydJWCOriGZQ5bYH75zCffGoy/QnL4HjfGDBvxpDRyuzExzzI1dahrxJcAdsmCcnn549Iq799HFjXcFjqlqEOhkGE26mG4w+qD3q6qlr2EkbJ7K6NgEAFiilafsev0JknW3hlMuHFzSzTeS++jsBSuU5RUBUlukkb3t8by7ich2lKEv4G2p7Hmf+GhELlKEgVuKetZm281xEjKjotUnin3fTZB85b+Ns3weL9Ijs2cT09fWxlPfCNJ9owd5gSrVsPJ7tbdiEs14JLr3Zk9OJTE7Yy+HKZHrHbuYstiqn6GWZ3RFQb+binwtOdXZeQTY6i/xRZUIAVSClW0a0RHnzphGyHJynrCERzD9bTUn2+75GXHJECrKbxKLjGwTkvX2aqI/rzjMdb1dzHx4Fnz5TyyGsk5WLP5Mj2wAj04spH5dg8kdsmqedsYdcgHGPVMsV08Bgx3wS0l+Zgc81QuLAdht+RA9wMJ128siYam7s1kV4UN2TdoRxxr33s+QeXKl+6meWK/R+buYtWBv2bGOspsKEbS3zRn12GriPU3eLFulDUwQSRAQA4lN8EKI0tB3dFa8oCYazRczomMD+DzjSQkGg/lFd3oTSYOc=
install:
- source ci/travis/install.sh
script:
- python ci/main.py recipes zechxu
