package:
  name: scikit-bio
  version: "0.4.2dev"

source:
  git_url: https://github.com/RNAer/scikit-bio.git
  git_tag: micronota

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - scikit-bio = scikit-bio:main
    #
    # Would create an entry point called scikit-bio that calls scikit-bio.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - bz2file >=0.98
    - lockfile >=0.10.2
    - cachecontrol >=0.11.5
    - contextlib2 >=0.4.0
    - decorator >=3.4.2
    - future >=0.14.3
    - ipython >=3.2.0
    - matplotlib >=1.4.3
    - natsort >=4.0.3
    - numpy >=1.9.2
    - pandas >=0.17.0
    - scipy >=0.15.1
    - six >=1.9.0
    - nose >=1.3.7

  run:
    - python
    - bz2file >=0.98
    - lockfile >=0.10.2
    - cachecontrol >=0.11.5
    - contextlib2 >=0.4.0
    - decorator >=3.4.2
    - future >=0.14.3
    - ipython >=3.2.0
    - matplotlib >=1.4.3
    - natsort >=4.0.3
    - numpy >=1.9.2
    - pandas >=0.17.0
    - scipy >=0.15.1
    - six >=1.9.0
    - nose >=1.3.7

test:
  # Python imports
  imports:
    - benchmarks
    - skbio
    - skbio.alignment
    - skbio.alignment._lib
    - skbio.alignment.tests
    - skbio.diversity
    - skbio.diversity.alpha
    - skbio.diversity.alpha.tests
    - skbio.diversity.beta
    - skbio.diversity.beta.tests
    - skbio.diversity.tests
    - skbio.io
    - skbio.io.format
    - skbio.io.format.tests
    - skbio.io.tests
    - skbio.sequence
    - skbio.sequence.tests
    - skbio.stats
    - skbio.stats.distance
    - skbio.stats.distance.tests
    - skbio.stats.evolve
    - skbio.stats.evolve.tests
    - skbio.stats.ordination
    - skbio.stats.ordination.tests
    - skbio.stats.tests
    - skbio.tests
    - skbio.tree
    - skbio.tree.tests
    - skbio.util
    - skbio.util.tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://scikit-bio.org
  license: BSD License
  summary: 'Data structures, algorithms and educational resources for bioinformatics.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
