package:
  name: deblur
  version: "0.0.1"

source:
  git_url: https://github.com/biocore/deblur.git
    
requirements:
  build:
    - python
    - setuptools
    - vsearch
    - mafft
    - sortmerna ==2.0
    - h5py

  run:
    - python
    - setuptools
    - vsearch
    - mafft
    - sortmerna ==2.0
    - h5py

test:
  imports:
    - deblur

about:
  home: https://github.com/biocore/deblur
  license: BSD license
