package:
  name: deblur
  version: "0.1.8"

source:
  git_url: https://github.com/biocore/deblur.git
    
requirements:
  build:
    - setuptools
    - python
    - scikit-bio
    - vsearch
    - mafft
    - sortmerna ==2.0
    - h5py
    - click
    - pip

  run:
    - setuptools
    - python
    - scikit-bio
    - vsearch
    - mafft
    - sortmerna ==2.0
    - h5py
    - click
    - pip

test:
  imports:
    - deblur

about:
  home: https://github.com/biocore/deblur
  license: BSD license
