package:
  name: burrito
  version: !!str 3b1dcc5

source:
  git_url: https://github.com/biocore/burrito.git

requirements:
  build:
    - python
    - future
  run:
    - python
test:
  # Python imports
  imports:
    - burrito

about:
  home: https://github.com/biocore/burrito
  summary: Python framework for controlling command-line applications
