package:
  name: anvio
  version: "v2.0.2"

source:
  git_url: https://github.com/meren/anvio.git
    
requirements:
  build:
    - python <3
    - setuptools
    - cython
    - prodigal
    - hmmer
    - bottle >0.12
    - pysam >0.9
    - scipy >0.13
    - scikit-learn >0.17
    - numpy >1.9
    - gsl
    - hdf5
    - pysam >=0.9

  run:
    - python <3
    - setuptools
    - cython
    - prodigal
    - hmmer
    - bottle >0.12
    - scipy >0.13
    - scikit-learn >0.17
    - numpy >1.9
    - gsl
    - hdf5
    - bottle >=0.12.9
    - pysam >=0.9

test:
  imports:
    - anvio

about:
  home: https://github.com/meren/anvio
  license: GPLv3 license
