package:
  name: vsearch
  version: "1.9.2"

source:
  git_rev: v1.9.2
  git_url: https://github.com/torognes/vsearch.git
 
requirements:
  build:
    - gcc

build:
  number: 0

 
test:
  commands:
    - vsearch -h
 
about:
  summary: VSEARCH, a versatile open source tool for metagenomics
  home: https://github.com/torognes/vsearch
  license: GPL/BSD
  license_file: LICENSE.txt
