package:
  name: vsearch
  version: "1.10.0"

source:
  git_rev: v1.10.0
  git_url: https://github.com/torognes/vsearch.git
  
build:
  number: 0

test:
  commands:
    - vsearch -h
 
about:
  summary: VSEARCH, a versatile open source tool for metagenomics
  home: https://github.com/torognes/vsearch
  license: GPL/BSD
  license_file: LICENSE.txt
